version: "2"
services:
  dojo:
    restart: always
    image: appsecpipeline/django-defectdojo:latest
    ports:
      - "8000:8000"
    volumes:
      - django-DefectDojo:/django-DefectDojo
    depends_on:
      - mysql
    env_file:
        - ./env/common.env
        - ./env/dojo.env
    command: bash /django-DefectDojo/docker/docker-startup.bash
  mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    env_file:
        - ./env/common.env
        - ./env/mysql.env
    environment:
      max_allowed_packet: "16M"
    volumes:
      - mysqldata:/var/lib/mysqldata/data/
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    environment:
     - DH_SIZE=512
    volumes_from:
      - dojo
    volumes:
      - nginxdata:/etc/nginx/external/
    depends_on:
      - dojo
volumes:
  mysqldata: {}
  django-DefectDojo: {}
  nginxdata: {}
